export {default as Header} from  './header/Header'
export {default as About} from  './about-us/About'
export {default as Services} from  './services/Services'
export {default as Blog} from  './blog/Blog'
export {default as Feature} from  './feature/Feature'
export {default as Footer} from  './footer/Footer'
export {default as Collection} from  './collection/Collection'